### ISSUE TITLE
Change meta description from "Stuff"

### ISSUE THREAD

**Issue by stuartsan** [aclu-people-power/map#97]
The HTML meta description tag says "Stuff" but it should say something probably a little more......specific, professional, etc.

**Comment by kpenning** [comment]
Can we copy all the meta tags from the current map?

**Comment by stuartsan** [comment]
👍  definitely

**Comment by stuartsan** [comment]
Here are all the meta tags I see that would probably make sense to just port directly over:
```
<meta name="application-name" content="People Power">
<meta name="description" content="We're organizing grassroots volunteers to fight against the worst abuses of the Trump administration.">
<meta property="og:image" content="http://s3.peoplepower.org/images/peoplepower-attendsocial.png">
<meta property="og:url" content="https://map.peoplepower.org/">
<meta property="og:title" content="Map: Join an ACLU People Power Action Event">
<meta property="og:description" content="We're organizing grassroots volunteers to fight against the worst abuses of the Trump administration.">
<meta property="og:site_name" content="PeoplePower.org">
<meta name="twitter:card" value="summary_large_image">
<meta name="twitter:site" content="@ACLU">
<meta name="twitter:creator" content="@ACLU">
```

**Comment by kpenning** [comment]
Looks right

On Apr 24, 2017 11:56 PM, "Stuart Sandine" <notifications@github.com> wrote:

Here are all the meta tags I see that would probably make sense to just
port directly over:

<meta name="application-name" content="People Power">
<meta name="description" content="We're organizing grassroots
volunteers to fight against the worst abuses of the Trump
administration.">
<meta property="og:image"
content="http://s3.peoplepower.org/images/peoplepower-attendsocial.png">
<meta property="og:url" content="https://map.peoplepower.org/">
<meta property="og:title" content="Map: Join an ACLU People Power Action Event">
<meta property="og:description" content="We're organizing grassroots
volunteers to fight against the worst abuses of the Trump
administration.">
<meta property="og:site_name" content="PeoplePower.org">
<meta name="twitter:card" value="summary_large_image">
<meta name="twitter:site" content="@ACLU">
<meta name="twitter:creator" content="@ACLU">

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/aclu-people-power/map/issues/97#issuecomment-296893561>,
or mute the thread
